/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pocan.pcompany.main;

import com.pocan.pcompany.modules.DatabaseOperations;
import com.pocan.pcompany.modules.FileModule;
import com.pocan.pcompany.modules.TrayIconDemo;
import com.pocan.pcompany.tasks.CheckTask;
import java.awt.AWTException;
import java.awt.SystemTray;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.sql.Connection;
import java.util.Timer;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Pocan
 */
public class LoginFrame extends javax.swing.JFrame {
        FileModule fileModule = new FileModule();

    DatabaseOperations databaseOperations = new DatabaseOperations();

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        fileModule.createFile("username");
        fileModule.createFile("password");
   
        username_value.setText(getUsername());
        password_value.setText(getPassword());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        left = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        Login_label = new javax.swing.JLabel();
        username_value = new javax.swing.JTextField();
        password_value = new javax.swing.JPasswordField();
        remember_me = new javax.swing.JCheckBox();
        forget_password_label = new javax.swing.JLabel();
        login_button = new com.k33ptoo.components.KButton();
        dont_have_account_label1 = new javax.swing.JLabel();
        dont_have_account_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        white_circle_label = new javax.swing.JLabel();
        orange_circle_label = new javax.swing.JLabel();
        red_circle_label = new javax.swing.JLabel();
        output = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(963, 590));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bgMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });

        left.setkEndColor(new java.awt.Color(204, 255, 255));
        left.setkStartColor(new java.awt.Color(0, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/ui.png"))); // NOI18N

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(65, 65, 65))
        );

        Login_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login_label.setForeground(new java.awt.Color(102, 102, 102));
        Login_label.setText("Giriş");

        username_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        username_value.setText("kullanıcı adı");
        username_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        password_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        password_value.setText("********************");
        password_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        remember_me.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        remember_me.setForeground(new java.awt.Color(153, 153, 153));
        remember_me.setText("  Beni Hatırla");

        forget_password_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forget_password_label.setForeground(new java.awt.Color(0, 204, 204));
        forget_password_label.setText("Şifremi unuttum?");

        login_button.setText("Giriş yap");
        login_button.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        login_button.setkBorderRadius(40);
        login_button.setkEndColor(new java.awt.Color(204, 255, 255));
        login_button.setkHoverColor(new java.awt.Color(51, 255, 255));
        login_button.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        login_button.setkHoverForeGround(new java.awt.Color(0, 204, 204));
        login_button.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        login_button.setkPressedColor(new java.awt.Color(102, 102, 255));
        login_button.setkStartColor(new java.awt.Color(0, 204, 204));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        dont_have_account_label1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        dont_have_account_label1.setForeground(new java.awt.Color(102, 102, 102));
        dont_have_account_label1.setText("Henüz hesabın yok mu?");

        dont_have_account_label2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        dont_have_account_label2.setForeground(new java.awt.Color(0, 204, 204));
        dont_have_account_label2.setText("Hesap oluştur");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/account.png"))); // NOI18N

        password_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/password.png"))); // NOI18N

        white_circle_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/white_circle25x25.png"))); // NOI18N

        orange_circle_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/orange_circle_25x25.png"))); // NOI18N

        red_circle_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/red_circle_25x25.png"))); // NOI18N
        red_circle_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                red_circle_labelMouseClicked(evt);
            }
        });

        output.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        output.setForeground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remember_me)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(username_value, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addComponent(dont_have_account_label1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                                .addComponent(dont_have_account_label2))
                                            .addComponent(forget_password_label)
                                            .addComponent(password_value)
                                            .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(password_label)))
                                .addContainerGap(48, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(red_circle_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orange_circle_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(white_circle_label)
                                .addGap(18, 18, 18))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(Login_label))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(white_circle_label)
                    .addComponent(orange_circle_label)
                    .addComponent(red_circle_label))
                .addGap(43, 43, 43)
                .addComponent(Login_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_label))
                .addGap(43, 43, 43)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remember_me)
                    .addComponent(forget_password_label))
                .addGap(34, 34, 34)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dont_have_account_label2)
                    .addComponent(dont_have_account_label1))
                .addGap(39, 39, 39)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseMoved
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgMouseMoved

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        output.setText("");
        if (databaseOperations.loginPanel(username_value.getText(),String.valueOf(password_value.getPassword()))) {
            RememberMe();
            System.out.println("Giriş başarılı");
            output.setText("                  Giriş yapılıyor...");
            output.setForeground(new java.awt.Color(51, 255, 0));
            new Main().setVisible(true);
            this.dispose();



        }
        else {
            System.out.println("Yanlış şifre.");
            output.setText("                  Yanlış şifre veya kullanıcı adı");
            output.setForeground(new java.awt.Color(255, 0, 0));


         
        }
     
    }//GEN-LAST:event_login_buttonActionPerformed

    public void RememberMe() {
       if (remember_me.isSelected()) {
           fileModule.writeFile("username", username_value.getText());
           fileModule.writeFile("password", String.valueOf(password_value.getPassword()));
           System.out.println("Başarıyla kullanıcı adı ve şifre kayıt edildi (Remember Me)");
                   
           
       } 
    }
    
    public String getUsername() {
        
        String username = fileModule.readFileAsString(System.getProperty("user.home") + File.separator + "Documents" + File.separator + "Heaven" + File.separator + "username.txt");
        if (!username.isEmpty()) {
            return username;
        }
        return "kullanıcı adı";
    }
    public String getPassword() {
        
        String password = fileModule.readFileAsString(System.getProperty("user.home") + File.separator + "Documents" + File.separator + "Heaven" + File.separator + "password.txt");
        if (!password.isEmpty()) {
            return password;
        }
        return "************";
    }
    private void red_circle_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_circle_labelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_red_circle_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Timer timer = new Timer();
        timer.schedule(new CheckTask(), 0,60000);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
                TrayIconDemo td = new TrayIconDemo();
                td.displayTray("Heaven", "Program başlatıldı");
                //FileModule fileModule = new FileModule();

                //fileModule.createFolder();
            }
        });
    }
    private int xx,xy;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_label;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dont_have_account_label1;
    private javax.swing.JLabel dont_have_account_label2;
    private javax.swing.JLabel forget_password_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private keeptoo.KGradientPanel left;
    public com.k33ptoo.components.KButton login_button;
    private javax.swing.JLabel orange_circle_label;
    private javax.swing.JLabel output;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_value;
    private javax.swing.JLabel red_circle_label;
    private javax.swing.JCheckBox remember_me;
    private javax.swing.JTextField username_value;
    private javax.swing.JLabel white_circle_label;
    // End of variables declaration//GEN-END:variables
}
