/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pocan.pcompany.main;

import com.pocan.pcompany.component.Header;
import com.pocan.pcompany.main.currency.Currency;
import com.pocan.pcompany.main.currency.CurrencyFactory;
import com.pocan.pcompany.main.currency.Moneys;
import com.pocan.pcompany.modules.DatabaseOperations;
import com.pocan.pcompany.modules.Notes;
import com.pocan.pcompany.modules.Statistic;
import com.pocan.pcompany.swing.HeaderColor;
import com.sun.org.apache.xerces.internal.impl.xs.SchemaGrammar;
import java.awt.Color;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ali
 */
public class Main extends javax.swing.JFrame {
    DefaultTableModel model,model1;
    DatabaseOperations databaseOperations = new DatabaseOperations();


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setBackground(new Color(0, 0, 0));
        model = (DefaultTableModel) log_history_table.getModel();
        model1 = (DefaultTableModel) notes_table.getModel();
        getTableLogs();
        updateNotes();
        updateLabels();
        updateTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bg = new com.pocan.pcompany.swing.RoundPanel();
        header2 = new com.pocan.pcompany.component.Header();
        menu2 = new com.pocan.pcompany.component.Menu();
        Screen = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        main_screen = new com.pocan.pcompany.swing.RoundPanel();
        roundPanel1 = new com.pocan.pcompany.swing.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alltime_dollar_text = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alltime_try_text = new javax.swing.JLabel();
        roundPanel2 = new com.pocan.pcompany.swing.RoundPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        daily_dollar_text = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        daily_try_text = new javax.swing.JLabel();
        roundPanel3 = new com.pocan.pcompany.swing.RoundPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        weekly_dollar_text = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        weekly_try_text = new javax.swing.JLabel();
        roundPanel4 = new com.pocan.pcompany.swing.RoundPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        monthly_dollar_text = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        monthly_try_text = new javax.swing.JLabel();
        dashboard_text = new javax.swing.JLabel();
        dashboard_sub_text = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        roundPanel5 = new com.pocan.pcompany.swing.RoundPanel();
        jLabel15 = new javax.swing.JLabel();
        roundPanel7 = new com.pocan.pcompany.swing.RoundPanel();
        customer_value = new javax.swing.JTextField();
        order_label = new javax.swing.JLabel();
        order_value = new javax.swing.JTextField();
        earn_value = new javax.swing.JTextField();
        customer_label = new javax.swing.JLabel();
        money_label = new javax.swing.JLabel();
        create_log_button = new com.k33ptoo.components.KButton();
        calendar_value = new javax.swing.JTextField();
        calendar_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        roundPanel8 = new com.pocan.pcompany.swing.RoundPanel();
        delete_notes_button = new com.k33ptoo.components.KButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes_table = new javax.swing.JTable();
        roundPanel9 = new com.pocan.pcompany.swing.RoundPanel();
        notebook_label = new javax.swing.JLabel();
        note_value = new javax.swing.JTextField();
        add_notes_button = new com.k33ptoo.components.KButton();
        jPanel4 = new javax.swing.JPanel();
        roundPanel6 = new com.pocan.pcompany.swing.RoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log_history_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        delete_button = new com.k33ptoo.components.KButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(17, 18, 21));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bgMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 717));

        main_screen.setBackground(new java.awt.Color(17, 18, 21));
        main_screen.setPreferredSize(new java.awt.Dimension(900, 667));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/money_icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("<html> Ömür boyu  <br> kazanç <html>");

        alltime_dollar_text.setBackground(new java.awt.Color(0, 0, 0));
        alltime_dollar_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        alltime_dollar_text.setText("$ 150");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/options_icon.png"))); // NOI18N

        alltime_try_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        alltime_try_text.setText("₺ 150");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alltime_dollar_text, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(alltime_try_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(alltime_dollar_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alltime_try_text)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        roundPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/money_icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("<html> Günlük ortalama  <br> kazanç <html>");

        daily_dollar_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        daily_dollar_text.setText("$ 150");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/options_icon.png"))); // NOI18N

        daily_try_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        daily_try_text.setText("₺ 150");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daily_dollar_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addComponent(daily_try_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(daily_dollar_text)
                .addGap(18, 18, 18)
                .addComponent(daily_try_text)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        roundPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/money_icon.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("<html> Haftalık ortalama  <br> kazanç <html>");

        weekly_dollar_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        weekly_dollar_text.setText("$ 150");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/options_icon.png"))); // NOI18N

        weekly_try_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        weekly_try_text.setText("₺ 150");

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weekly_dollar_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addComponent(weekly_try_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9))
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(weekly_dollar_text)
                .addGap(18, 18, 18)
                .addComponent(weekly_try_text)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        roundPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/money_icon.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("<html> Aylık ortalama  <br> kazanç <html>");

        monthly_dollar_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        monthly_dollar_text.setText("$ 150");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/options_icon.png"))); // NOI18N

        monthly_try_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        monthly_try_text.setText("₺ 150");

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthly_dollar_text, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(monthly_try_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13))
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(monthly_dollar_text)
                .addGap(18, 18, 18)
                .addComponent(monthly_try_text)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        dashboard_text.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        dashboard_text.setForeground(new java.awt.Color(255, 255, 255));
        dashboard_text.setText("Ana Sayfa");

        dashboard_sub_text.setForeground(new java.awt.Color(102, 102, 102));
        dashboard_sub_text.setText("Şirketinizin büyümesini analiz edin.");

        javax.swing.GroupLayout main_screenLayout = new javax.swing.GroupLayout(main_screen);
        main_screen.setLayout(main_screenLayout);
        main_screenLayout.setHorizontalGroup(
            main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_screenLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard_text)
                    .addComponent(dashboard_sub_text)
                    .addGroup(main_screenLayout.createSequentialGroup()
                        .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        main_screenLayout.setVerticalGroup(
            main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_screenLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(dashboard_text)
                .addGap(18, 18, 18)
                .addComponent(dashboard_sub_text)
                .addGap(50, 50, 50)
                .addGroup(main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(main_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(main_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Screen.addTab("tab1", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 717));

        roundPanel5.setBackground(new java.awt.Color(17, 18, 21));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kayıt oluştur");

        roundPanel7.setBackground(new java.awt.Color(255, 255, 255));

        customer_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        customer_value.setText("0");
        customer_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        order_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/order.png"))); // NOI18N

        order_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        order_value.setText("0");
        order_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        earn_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        earn_value.setText("0");
        earn_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        customer_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/customer.png"))); // NOI18N

        money_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/money.png"))); // NOI18N

        create_log_button.setText("Oluştur");
        create_log_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        create_log_button.setkEndColor(new java.awt.Color(255, 255, 255));
        create_log_button.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        create_log_button.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        create_log_button.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        create_log_button.setkSelectedColor(new java.awt.Color(0, 0, 0));
        create_log_button.setkStartColor(new java.awt.Color(0, 0, 0));
        create_log_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_log_buttonActionPerformed(evt);
            }
        });

        calendar_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        calendar_value.setText("18/09/1990");
        calendar_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        calendar_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/calendar.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel7Layout = new javax.swing.GroupLayout(roundPanel7);
        roundPanel7.setLayout(roundPanel7Layout);
        roundPanel7Layout.setHorizontalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel7Layout.createSequentialGroup()
                .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel7Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(earn_value, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(order_value, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customer_value, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calendar_value, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(order_label)
                            .addComponent(money_label)
                            .addComponent(customer_label)
                            .addComponent(calendar_label)))
                    .addGroup(roundPanel7Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(create_log_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        roundPanel7Layout.setVerticalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel7Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendar_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendar_label))
                .addGap(27, 27, 27)
                .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer_label)
                    .addComponent(customer_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(order_label)
                    .addComponent(order_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(earn_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(money_label))
                .addGap(53, 53, 53)
                .addComponent(create_log_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Büyümenizi analiz edebilmemiz için kayıt oluşturun.");

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                        .addComponent(roundPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(298, 298, 298))))
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(roundPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Screen.addTab("tab2", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(900, 717));

        roundPanel8.setBackground(new java.awt.Color(17, 18, 21));

        delete_notes_button.setText("Sil");
        delete_notes_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete_notes_button.setkEndColor(new java.awt.Color(255, 255, 255));
        delete_notes_button.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        delete_notes_button.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        delete_notes_button.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        delete_notes_button.setkSelectedColor(new java.awt.Color(0, 0, 0));
        delete_notes_button.setkStartColor(new java.awt.Color(0, 0, 0));
        delete_notes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_notes_buttonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Notlarım");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Aklınıza gelen şeyleri unutmayın kayıt edin");

        notes_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Notlar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notes_table.setGridColor(new java.awt.Color(204, 255, 255));
        notes_table.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(notes_table);
        if (notes_table.getColumnModel().getColumnCount() > 0) {
            notes_table.getColumnModel().getColumn(0).setResizable(false);
        }

        roundPanel9.setBackground(new java.awt.Color(255, 255, 255));

        notebook_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/notebook.png"))); // NOI18N

        note_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        note_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout roundPanel9Layout = new javax.swing.GroupLayout(roundPanel9);
        roundPanel9.setLayout(roundPanel9Layout);
        roundPanel9Layout.setHorizontalGroup(
            roundPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel9Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(note_value, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notebook_label)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        roundPanel9Layout.setVerticalGroup(
            roundPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel9Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(roundPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(note_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notebook_label))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        add_notes_button.setText("Ekle");
        add_notes_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_notes_button.setkEndColor(new java.awt.Color(255, 255, 255));
        add_notes_button.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        add_notes_button.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        add_notes_button.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        add_notes_button.setkSelectedColor(new java.awt.Color(0, 0, 0));
        add_notes_button.setkStartColor(new java.awt.Color(0, 0, 0));
        add_notes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_notes_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel8Layout = new javax.swing.GroupLayout(roundPanel8);
        roundPanel8.setLayout(roundPanel8Layout);
        roundPanel8Layout.setHorizontalGroup(
            roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel8Layout.createSequentialGroup()
                .addGroup(roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel8Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(add_notes_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(delete_notes_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel8Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roundPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(roundPanel8Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel17))
                    .addGroup(roundPanel8Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel18)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        roundPanel8Layout.setVerticalGroup(
            roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(roundPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_notes_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_notes_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(roundPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Screen.addTab("tab3", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(900, 717));

        roundPanel6.setBackground(new java.awt.Color(17, 18, 21));

        log_history_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarih", "Müşteri", "Sipariş", "Cüro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        log_history_table.setFocusable(false);
        log_history_table.setGridColor(new java.awt.Color(128, 128, 128));
        log_history_table.setRowHeight(25);
        log_history_table.setSelectionBackground(new java.awt.Color(0, 0, 0));
        log_history_table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        log_history_table.setShowHorizontalLines(true);
        log_history_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(log_history_table);
        if (log_history_table.getColumnModel().getColumnCount() > 0) {
            log_history_table.getColumnModel().getColumn(0).setResizable(false);
            log_history_table.getColumnModel().getColumn(1).setResizable(false);
            log_history_table.getColumnModel().getColumn(1).setHeaderValue("Müşteri");
            log_history_table.getColumnModel().getColumn(2).setResizable(false);
            log_history_table.getColumnModel().getColumn(2).setHeaderValue("Sipariş");
            log_history_table.getColumnModel().getColumn(3).setResizable(false);
            log_history_table.getColumnModel().getColumn(3).setHeaderValue("Cüro");
        }

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sistem Kayıtları");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Şirketinizin özet kayıtlarını inceleyin.");

        delete_button.setText("Sil");
        delete_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete_button.setkEndColor(new java.awt.Color(255, 255, 255));
        delete_button.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        delete_button.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        delete_button.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        delete_button.setkSelectedColor(new java.awt.Color(0, 0, 0));
        delete_button.setkStartColor(new java.awt.Color(0, 0, 0));
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel6Layout = new javax.swing.GroupLayout(roundPanel6);
        roundPanel6.setLayout(roundPanel6Layout);
        roundPanel6Layout.setHorizontalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel6Layout.createSequentialGroup()
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundPanel6Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        roundPanel6Layout.setVerticalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(roundPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Screen.addTab("tab4", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        Screen.addTab("tab5", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        Screen.addTab("tab6", jPanel6);

        getContentPane().add(Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, -35, 900, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseMoved
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgMouseMoved

    private void create_log_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_log_buttonActionPerformed
        String date = calendar_value.getText();
        int customer = Integer.valueOf(customer_value.getText());
        int order = Integer.valueOf(order_value.getText());
        int money = Integer.valueOf(earn_value.getText());
      //  Date d = new Date();
      //  DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

      //  String date = dateFormat.format(d);
 
        if (customer >= 0 && order >= 0 && money >= 0 && !databaseOperations.dateCheck().contains(date)) {
            databaseOperations.addStatistic(date, customer, order, money);
            JOptionPane.showMessageDialog(this,"Başarıyla günlük kayıtı oluşturdun.","Başarılı",JOptionPane.PLAIN_MESSAGE);
            customer_value.setText("0");
            order_value.setText("0");
            earn_value.setText("0");
            getTableLogs();
            updateLabels();
           
        }
        else {
            JOptionPane.showMessageDialog(this,"Bugün kayıt yapıldı.","Hata",JOptionPane.ERROR_MESSAGE);
            customer_value.setText("0");
            order_value.setText("0");
            earn_value.setText("0");
     
        }
        
        
     
     





    }//GEN-LAST:event_create_log_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        int selectedRow = log_history_table.getSelectedRow();
        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Veri tabanı şuan da boş.","Hata",JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this,"Herhangi bir değer seçilmedi.","Hata",JOptionPane.ERROR_MESSAGE);
      
            }
        }
        else {
            String date = (String) model.getValueAt(selectedRow, 0);
            databaseOperations.deleteStatistic(date);
            getTableLogs();
            updateLabels();
            JOptionPane.showMessageDialog(this,"Başarıyla seçmiş olduğunuz veriyi sildiniz.","Başarılı",JOptionPane.PLAIN_MESSAGE);

        }









    }//GEN-LAST:event_delete_buttonActionPerformed

    private void delete_notes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_notes_buttonActionPerformed
        int selectedRow = notes_table.getSelectedRow();
        if (selectedRow == -1) {
            if (model1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Notlar şuan da boş.","Hata",JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this,"Herhangi bir not seçilmedi.","Hata",JOptionPane.ERROR_MESSAGE);
      
            }
        }
        else {
            String note = (String) model1.getValueAt(selectedRow, 0);
            databaseOperations.deleteNote(note);
            updateNotes();
            updateLabels();
            JOptionPane.showMessageDialog(this,"Başarıyla seçmiş olduğunuz notu sildiniz.","Başarılı",JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_delete_notes_buttonActionPerformed

    private void add_notes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_notes_buttonActionPerformed
        String note = note_value.getText();
        if (!note.isEmpty()) {
            databaseOperations.addNotes(note);
            note_value.setText("");
            JOptionPane.showMessageDialog(this,"Başarıyla yeni notunuzu eklediniz.","Başarılı",JOptionPane.PLAIN_MESSAGE);
            updateNotes();

        }
        else {
            JOptionPane.showMessageDialog(this,"Notun içerisi boş olamaz.","Hata",JOptionPane.ERROR_MESSAGE);
 
        }

    }//GEN-LAST:event_add_notes_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void updateTables() {

        log_history_table.getTableHeader().setDefaultRenderer(new HeaderColor());
        notes_table.getTableHeader().setDefaultRenderer(new HeaderColor());
        
    }
    
    public void resetSelectedRows() {
        log_history_table.getSelectionModel().clearSelection();
        notes_table.getSelectionModel().clearSelection();
       
        
    }
    
    public void updateLabels() {
        float total_money_dollar = databaseOperations.getMoney(databaseOperations.getEarn(), databaseOperations.calculateTax(databaseOperations.getEarn()));
        float total_money_try = databaseOperations.convertTRY(total_money_dollar);
        int amount = databaseOperations.getAmountOfLogs();
        
        float daily_money_dollar = total_money_dollar / amount;
        float daily_money_try = databaseOperations.convertTRY(daily_money_dollar);
        
        
        float weekly_money_dollar = daily_money_dollar * 7;
        float weekly_money_try = databaseOperations.convertTRY(weekly_money_dollar);

        float monthly_money_dollar = daily_money_dollar * 30;
        float monthly_money_try = databaseOperations.convertTRY(monthly_money_dollar);
               
        
        
        
        alltime_try_text.setText("₺ " + databaseOperations.getHumanReadablePriceFromNumber((long) total_money_try));
        alltime_dollar_text.setText("$ " + databaseOperations.getHumanReadablePriceFromNumber((long) total_money_dollar));
        
        daily_try_text.setText("₺ " + databaseOperations.getHumanReadablePriceFromNumber((long) daily_money_try));
        daily_dollar_text.setText("$ " + databaseOperations.getHumanReadablePriceFromNumber((long) daily_money_dollar));
    
        weekly_try_text.setText("₺ " + databaseOperations.getHumanReadablePriceFromNumber((long) weekly_money_try));
        weekly_dollar_text.setText("$ " + databaseOperations.getHumanReadablePriceFromNumber((long) weekly_money_dollar));
        monthly_try_text.setText("₺ " + databaseOperations.getHumanReadablePriceFromNumber((long) monthly_money_try));
        monthly_dollar_text.setText("$ " + databaseOperations.getHumanReadablePriceFromNumber((long) monthly_money_dollar));
        Date d = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        calendar_value.setText(dateFormat.format(d));

        
    }
    
    public void updateNotes() {
        model1.setRowCount(0);
        ArrayList<Notes> notes = new ArrayList<Notes>();
        notes = databaseOperations.getNotes(); 
        if (notes != null) {
            
            for(Notes n : notes) {
                Object[] add = {n.getNote()};
                model1.addRow(add);
                
            }
            
        }
        
    }
    
    public JFrame getFrame() {
        
        return this;
    }
    
    
    
    public void getTableLogs() {
        model.setRowCount(0);
        ArrayList<Statistic> statistic = new ArrayList<Statistic>();
        statistic = databaseOperations.getStatistic();
        

        

        
        
        if (statistic != null) {
            
            for(Statistic s : statistic) {
                Object[] add = {s.getDate(),s.getCustomer(),s.getOrder(),s.getEarn()};
                model.addRow(add);
                
            }
            
        }
        
        
    }
    
    public void setScreen(int index) {
        Screen.setSelectedIndex(index);
        
    }
    
   public javax.swing.JTabbedPane getScreen() {
        return Screen;
    }


   



    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane Screen;
    private com.k33ptoo.components.KButton add_notes_button;
    private javax.swing.JLabel alltime_dollar_text;
    private javax.swing.JLabel alltime_try_text;
    private com.pocan.pcompany.swing.RoundPanel bg;
    private javax.swing.JLabel calendar_label;
    private javax.swing.JTextField calendar_value;
    private com.k33ptoo.components.KButton create_log_button;
    private javax.swing.JLabel customer_label;
    private javax.swing.JTextField customer_value;
    private javax.swing.JLabel daily_dollar_text;
    private javax.swing.JLabel daily_try_text;
    private javax.swing.JLabel dashboard_sub_text;
    private javax.swing.JLabel dashboard_text;
    private com.k33ptoo.components.KButton delete_button;
    private com.k33ptoo.components.KButton delete_notes_button;
    private javax.swing.JTextField earn_value;
    private com.pocan.pcompany.component.Header header2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable log_history_table;
    private com.pocan.pcompany.swing.RoundPanel main_screen;
    private com.pocan.pcompany.component.Menu menu2;
    private javax.swing.JLabel money_label;
    private javax.swing.JLabel monthly_dollar_text;
    private javax.swing.JLabel monthly_try_text;
    private javax.swing.JTextField note_value;
    private javax.swing.JLabel notebook_label;
    public javax.swing.JTable notes_table;
    private javax.swing.JLabel order_label;
    private javax.swing.JTextField order_value;
    private com.pocan.pcompany.swing.RoundPanel roundPanel1;
    private com.pocan.pcompany.swing.RoundPanel roundPanel2;
    private com.pocan.pcompany.swing.RoundPanel roundPanel3;
    private com.pocan.pcompany.swing.RoundPanel roundPanel4;
    private com.pocan.pcompany.swing.RoundPanel roundPanel5;
    private com.pocan.pcompany.swing.RoundPanel roundPanel6;
    private com.pocan.pcompany.swing.RoundPanel roundPanel7;
    private com.pocan.pcompany.swing.RoundPanel roundPanel8;
    private com.pocan.pcompany.swing.RoundPanel roundPanel9;
    private javax.swing.JLabel weekly_dollar_text;
    private javax.swing.JLabel weekly_try_text;
    // End of variables declaration//GEN-END:variables
    private int xx, xy;

}
