package com.pocan.pcompany.component;

import com.pocan.pcompany.main.Main;
import com.pocan.pcompany.swing.RoundPanel;
import java.awt.Color;
import javafx.stage.Screen;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;

public class Menu extends javax.swing.JPanel {

    public Menu() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new com.pocan.pcompany.swing.RoundPanel();
        home_button = new com.pocan.pcompany.swing.RoundPanel();
        home_label = new javax.swing.JLabel();
        home_button1 = new com.pocan.pcompany.swing.RoundPanel();
        home_label1 = new javax.swing.JLabel();
        home_button2 = new com.pocan.pcompany.swing.RoundPanel();
        home_label2 = new javax.swing.JLabel();
        home_button3 = new com.pocan.pcompany.swing.RoundPanel();
        home_label3 = new javax.swing.JLabel();
        imageAvatar1 = new com.pocan.pcompany.swing.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();

        roundPanel1.setBackground(new java.awt.Color(17, 18, 21));

        home_button.setBackground(new java.awt.Color(255, 255, 255));
        home_button.setForeground(new java.awt.Color(255, 255, 255));
        home_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_buttonMouseClicked(evt);
            }
        });

        home_label.setBackground(new java.awt.Color(17, 18, 21));
        home_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/home_icon.png"))); // NOI18N

        javax.swing.GroupLayout home_buttonLayout = new javax.swing.GroupLayout(home_button);
        home_button.setLayout(home_buttonLayout);
        home_buttonLayout.setHorizontalGroup(
            home_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_buttonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home_label)
                .addContainerGap())
        );
        home_buttonLayout.setVerticalGroup(
            home_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_buttonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(home_label))
        );

        home_button1.setBackground(new java.awt.Color(17, 18, 21));
        home_button1.setForeground(new java.awt.Color(255, 255, 255));
        home_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_button1MouseClicked(evt);
            }
        });

        home_label1.setBackground(new java.awt.Color(51, 51, 51));
        home_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/credit_card_icon.png"))); // NOI18N

        javax.swing.GroupLayout home_button1Layout = new javax.swing.GroupLayout(home_button1);
        home_button1.setLayout(home_button1Layout);
        home_button1Layout.setHorizontalGroup(
            home_button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_button1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home_label1)
                .addContainerGap())
        );
        home_button1Layout.setVerticalGroup(
            home_button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_button1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(home_label1))
        );

        home_button2.setBackground(new java.awt.Color(17, 18, 21));
        home_button2.setForeground(new java.awt.Color(255, 255, 255));
        home_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_button2MouseClicked(evt);
            }
        });

        home_label2.setBackground(new java.awt.Color(51, 51, 51));
        home_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/light_icon.png"))); // NOI18N

        javax.swing.GroupLayout home_button2Layout = new javax.swing.GroupLayout(home_button2);
        home_button2.setLayout(home_button2Layout);
        home_button2Layout.setHorizontalGroup(
            home_button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_button2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home_label2)
                .addContainerGap())
        );
        home_button2Layout.setVerticalGroup(
            home_button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_button2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(home_label2))
        );

        home_button3.setBackground(new java.awt.Color(17, 18, 21));
        home_button3.setForeground(new java.awt.Color(255, 255, 255));
        home_button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_button3MouseClicked(evt);
            }
        });

        home_label3.setBackground(new java.awt.Color(51, 51, 51));
        home_label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/box_icon.png"))); // NOI18N

        javax.swing.GroupLayout home_button3Layout = new javax.swing.GroupLayout(home_button3);
        home_button3.setLayout(home_button3Layout);
        home_button3Layout.setHorizontalGroup(
            home_button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_button3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home_label3)
                .addContainerGap())
        );
        home_button3Layout.setVerticalGroup(
            home_button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_button3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(home_label3))
        );

        imageAvatar1.setBorderSize(2);
        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/runheaven.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("RunHeaven");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(home_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home_button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void home_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_buttonMouseClicked
        resetPanelColor(getSelectedMenu(), defaultMenuColor);
        changePanelColor(home_button, selectedMenuColor);
        selectedMenuPanel = home_button;
        Main.Screen.setSelectedIndex(0);
        



    }//GEN-LAST:event_home_buttonMouseClicked

    private void home_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button1MouseClicked
        resetPanelColor(getSelectedMenu(), defaultMenuColor);
        changePanelColor(home_button1, selectedMenuColor);
        selectedMenuPanel = home_button1;
        Main.Screen.setSelectedIndex(1);


    }//GEN-LAST:event_home_button1MouseClicked

    private void home_button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button2MouseClicked
        resetPanelColor(getSelectedMenu(), defaultMenuColor);
        changePanelColor(home_button2, selectedMenuColor);
        selectedMenuPanel = home_button2;
        Main.Screen.setSelectedIndex(2);


    }//GEN-LAST:event_home_button2MouseClicked

    private void home_button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button3MouseClicked
        resetPanelColor(getSelectedMenu(), defaultMenuColor);
        changePanelColor(home_button3, selectedMenuColor);
        selectedMenuPanel = home_button3;
        Main.Screen.setSelectedIndex(3);


    }//GEN-LAST:event_home_button3MouseClicked

    private void changePanelColor(RoundPanel panel, Color color) {
        panel.setBackground(color);

    }

    private void resetPanelColor(RoundPanel panel, Color color) {

        panel.setBackground(color);

    }

    private void setMenuIndex(javax.swing.JTabbedPane panel, int index) {
        panel.setSelectedIndex(index);

    }

    private RoundPanel getSelectedMenu() {
        if (selectedMenuPanel != null) {
            return selectedMenuPanel;

        }
        return home_button;
    }

    public RoundPanel selectedMenuPanel;
    private Color defaultMenuColor = new Color(17, 18, 21);
    private Color selectedMenuColor = new Color(255, 255, 255);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pocan.pcompany.swing.RoundPanel home_button;
    private com.pocan.pcompany.swing.RoundPanel home_button1;
    private com.pocan.pcompany.swing.RoundPanel home_button2;
    private com.pocan.pcompany.swing.RoundPanel home_button3;
    private javax.swing.JLabel home_label;
    private javax.swing.JLabel home_label1;
    private javax.swing.JLabel home_label2;
    private javax.swing.JLabel home_label3;
    private com.pocan.pcompany.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private com.pocan.pcompany.swing.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
