
package com.pocan.pcompany.component;

import com.pocan.pcompany.main.Main;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;


public class Header extends javax.swing.JPanel {

 
    public Header() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(17, 18, 21));
        
    }
    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        Area area = new Area(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        area.add(new Area(new Rectangle2D.Double(0, 20, getWidth(), getHeight())));
        g2.fill(area);
        g2.dispose();
        super.paint(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        red_circle_icon = new javax.swing.JLabel();
        orange_circle_icon = new javax.swing.JLabel();
        white_circle_icon = new javax.swing.JLabel();

        red_circle_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/red_circle_25x25.png"))); // NOI18N
        red_circle_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                red_circle_iconMouseClicked(evt);
            }
        });

        orange_circle_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/orange_circle_25x25.png"))); // NOI18N
        orange_circle_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orange_circle_iconMouseClicked(evt);
            }
        });

        white_circle_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pocan/pcompany/icon/white_circle25x25.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(red_circle_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orange_circle_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(white_circle_icon)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(white_circle_icon)
                    .addComponent(orange_circle_icon)
                    .addComponent(red_circle_icon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void red_circle_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_circle_iconMouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_red_circle_iconMouseClicked

    private void orange_circle_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orange_circle_iconMouseClicked


    JFrame f = (JFrame) SwingUtilities.getAncestorOfClass(Main.class, this);
    f.setState(Frame.ICONIFIED);


        
    }//GEN-LAST:event_orange_circle_iconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel orange_circle_icon;
    private javax.swing.JLabel red_circle_icon;
    private javax.swing.JLabel white_circle_icon;
    // End of variables declaration//GEN-END:variables
}
